# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

logging:
  file:
    name: logs/service.log
  level:
    com: WARN
    net: WARN
    org: WARN
    au.com.totemsoft.crm: INFO

server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: Client Service
  jpa.open-in-view: false
